### ISSUE TITLE
TypeError in calling initial_func

### ISSUE THREAD

**Issue by chickencoder** [crossroadchurch/malachi#2]
Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "malachi_server.py", line 77, in responder
    await initial_func(websocket)
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "malachi_server.py", line 77, in responder
    await initial_func(websocket)
TypeError: <lambda>() takes 0 positional arguments but 1 was given

Not sure if this came in after making changes in open pull request or not

**Comment by nikukatansa** [comment]
Try the latest commit, which should have fixed the problem!  The TypeError was being caused by how I was switching between the different _init functions.  I hadn't set up a "route" for display_init, which caused the error and also meant that self.display_init wasn't being called.
